//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maricopa.Services {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://com.wiznet/filingassemblymde/types", ConfigurationName="Maricopa.Services.FilingAssemblyMDE")]
    public interface FilingAssemblyMDE {
        
        // CODEGEN: Generating message contract since the operation notifyFilingReviewComplete is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Maricopa.Services.notifyFilingReviewCompleteResponse notifyFilingReviewComplete(Maricopa.Services.notifyFilingReviewCompleteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class notifyFilingReviewCompleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.wiznet/filingassemblymde/types", Order=0)]
        public object notifyFilingReviewComplete;
        
        public notifyFilingReviewCompleteRequest() {
        }
        
        public notifyFilingReviewCompleteRequest(object notifyFilingReviewComplete) {
            this.notifyFilingReviewComplete = notifyFilingReviewComplete;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class notifyFilingReviewCompleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://com.wiznet/filingassemblymde/types", Order=0)]
        public object notifyFilingReviewCompleteReturn;
        
        public notifyFilingReviewCompleteResponse() {
        }
        
        public notifyFilingReviewCompleteResponse(object notifyFilingReviewCompleteReturn) {
            this.notifyFilingReviewCompleteReturn = notifyFilingReviewCompleteReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FilingAssemblyMDEChannel : Maricopa.Services.FilingAssemblyMDE, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FilingAssemblyMDEClient : System.ServiceModel.ClientBase<Maricopa.Services.FilingAssemblyMDE>, Maricopa.Services.FilingAssemblyMDE {
        
        public FilingAssemblyMDEClient() {
        }
        
        public FilingAssemblyMDEClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FilingAssemblyMDEClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FilingAssemblyMDEClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FilingAssemblyMDEClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Maricopa.Services.notifyFilingReviewCompleteResponse Maricopa.Services.FilingAssemblyMDE.notifyFilingReviewComplete(Maricopa.Services.notifyFilingReviewCompleteRequest request) {
            return base.Channel.notifyFilingReviewComplete(request);
        }
        
        public object notifyFilingReviewComplete(object notifyFilingReviewComplete1) {
            Maricopa.Services.notifyFilingReviewCompleteRequest inValue = new Maricopa.Services.notifyFilingReviewCompleteRequest();
            inValue.notifyFilingReviewComplete = notifyFilingReviewComplete1;
            Maricopa.Services.notifyFilingReviewCompleteResponse retVal = ((Maricopa.Services.FilingAssemblyMDE)(this)).notifyFilingReviewComplete(inValue);
            return retVal.notifyFilingReviewCompleteReturn;
        }
    }
}
